apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "morvo.fullname" . }}
  labels:
    {{- include "morvo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "morvo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "morvo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: morvo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }} 