"""Create initial tables

Revision ID: 1ac826f6e3f2
Revises:
Create Date: 2025-06-27 17:44:47.153314

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ac826f6e3f2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "business_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("website", sa.String(), nullable=False),
        sa.Column("industry", sa.String(), nullable=False),
        sa.Column("company_size", sa.String(), nullable=False),
        sa.Column("target_audience", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("locations", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("marketing_goals", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("competitors", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("current_channels", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("pain_points", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("social_profiles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("analytics_connected", sa.Boolean(), nullable=False),
        sa.Column("crm_platform", sa.String(), nullable=True),
        sa.Column("brand_voice", sa.String(), nullable=False),
        sa.Column("brand_values", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("usp", sa.String(), nullable=False),
        sa.Column("content_preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("automation_level", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subscription_tier", sa.String(), nullable=False),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("intelligence_last_updated", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("business_profiles")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
