"""add_enterprise_models_complete_schema

Revision ID: 7d397c2cc026
Revises: c44ae019799c
Create Date: 2025-06-29 01:23:38.489729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d397c2cc026'
down_revision: Union[str, None] = 'c44ae019799c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('successful_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('average_response_time_ms', sa.Float(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('new_registrations', sa.Integer(), nullable=False),
    sa.Column('completed_onboardings', sa.Integer(), nullable=False),
    sa.Column('agent_interactions', sa.JSON(), nullable=False),
    sa.Column('agent_success_rates', sa.JSON(), nullable=False),
    sa.Column('agent_response_times', sa.JSON(), nullable=False),
    sa.Column('total_api_calls', sa.Integer(), nullable=False),
    sa.Column('api_costs_usd', sa.Float(), nullable=False),
    sa.Column('api_success_rates', sa.JSON(), nullable=False),
    sa.Column('total_business_value_generated', sa.Float(), nullable=False),
    sa.Column('customer_satisfaction_average', sa.Float(), nullable=True),
    sa.Column('revenue_impact_usd', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('critical_errors', sa.Integer(), nullable=False),
    sa.Column('error_types', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_date'), 'system_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('conversation_type', sa.String(length=50), nullable=False),
    sa.Column('conversation_stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completion_reason', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('primary_goal', sa.String(length=200), nullable=True),
    sa.Column('key_outcomes', sa.JSON(), nullable=True),
    sa.Column('primary_agent', sa.String(length=50), nullable=False),
    sa.Column('involved_agents', sa.JSON(), nullable=False),
    sa.Column('agent_handoffs', sa.JSON(), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('user_messages_count', sa.Integer(), nullable=False),
    sa.Column('agent_messages_count', sa.Integer(), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=True),
    sa.Column('user_satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('conversation_quality_score', sa.Float(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('business_value_generated', sa.String(length=100), nullable=True),
    sa.Column('actionable_insights_count', sa.Integer(), nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=True)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('cultural_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cultural_background', sa.String(length=100), nullable=True),
    sa.Column('native_language', sa.String(length=50), nullable=False),
    sa.Column('secondary_languages', sa.JSON(), nullable=True),
    sa.Column('cultural_fluency_level', sa.String(length=50), nullable=False),
    sa.Column('religious_considerations', sa.Boolean(), nullable=False),
    sa.Column('halal_marketing_required', sa.Boolean(), nullable=False),
    sa.Column('prayer_time_awareness', sa.Boolean(), nullable=False),
    sa.Column('ramadan_marketing_adjustments', sa.Boolean(), nullable=False),
    sa.Column('primary_region', sa.String(length=50), nullable=True),
    sa.Column('regional_dialect_preference', sa.String(length=50), nullable=True),
    sa.Column('local_market_focus', sa.Boolean(), nullable=False),
    sa.Column('regional_business_customs', sa.JSON(), nullable=True),
    sa.Column('business_relationship_style', sa.String(length=50), nullable=False),
    sa.Column('hierarchy_awareness', sa.String(length=50), nullable=False),
    sa.Column('decision_making_style', sa.String(length=50), nullable=False),
    sa.Column('communication_directness', sa.String(length=50), nullable=False),
    sa.Column('family_business_consideration', sa.Boolean(), nullable=False),
    sa.Column('gender_considerations', sa.Boolean(), nullable=False),
    sa.Column('social_media_preferences', sa.JSON(), nullable=True),
    sa.Column('influencer_marketing_acceptance', sa.String(length=50), nullable=False),
    sa.Column('traditional_values_importance', sa.Integer(), nullable=False),
    sa.Column('modern_approach_openness', sa.Integer(), nullable=False),
    sa.Column('innovation_acceptance', sa.String(length=50), nullable=False),
    sa.Column('vision_2030_alignment', sa.Boolean(), nullable=False),
    sa.Column('sustainability_focus', sa.Boolean(), nullable=False),
    sa.Column('diversification_support', sa.Boolean(), nullable=False),
    sa.Column('local_content_preference', sa.Integer(), nullable=False),
    sa.Column('cultural_taboos_awareness', sa.JSON(), nullable=False),
    sa.Column('preferred_imagery_style', sa.String(length=50), nullable=True),
    sa.Column('color_symbolism_awareness', sa.Boolean(), nullable=False),
    sa.Column('text_direction_preference', sa.String(length=10), nullable=False),
    sa.Column('islamic_calendar_awareness', sa.Boolean(), nullable=False),
    sa.Column('national_holidays_consideration', sa.Boolean(), nullable=False),
    sa.Column('seasonal_marketing_preferences', sa.JSON(), nullable=True),
    sa.Column('cultural_events_integration', sa.Boolean(), nullable=False),
    sa.Column('formal_address_preference', sa.Boolean(), nullable=False),
    sa.Column('honorific_usage', sa.Boolean(), nullable=False),
    sa.Column('storytelling_appreciation', sa.Boolean(), nullable=False),
    sa.Column('metaphor_usage_comfort', sa.String(length=50), nullable=False),
    sa.Column('local_competitor_awareness', sa.Boolean(), nullable=False),
    sa.Column('international_brand_perception', sa.String(length=50), nullable=False),
    sa.Column('price_sensitivity_level', sa.String(length=50), nullable=False),
    sa.Column('quality_vs_price_priority', sa.String(length=50), nullable=False),
    sa.Column('social_media_activity_level', sa.String(length=50), nullable=False),
    sa.Column('e_commerce_comfort', sa.String(length=50), nullable=False),
    sa.Column('mobile_first_preference', sa.Boolean(), nullable=False),
    sa.Column('digital_payment_acceptance', sa.String(length=50), nullable=False),
    sa.Column('custom_cultural_notes', sa.Text(), nullable=True),
    sa.Column('cultural_mentor_recommendations', sa.JSON(), nullable=True),
    sa.Column('cultural_learning_resources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_cultural_contexts_id'), 'cultural_contexts', ['id'], unique=False)
    op.create_table('marketing_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('insight_data', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('data_sources', sa.JSON(), nullable=False),
    sa.Column('generated_by_agent', sa.String(length=100), nullable=False),
    sa.Column('estimated_impact', sa.String(length=50), nullable=False),
    sa.Column('implementation_effort', sa.String(length=50), nullable=False),
    sa.Column('estimated_roi', sa.Float(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('implemented', sa.Boolean(), nullable=False),
    sa.Column('implementation_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_insights_id'), 'marketing_insights', ['id'], unique=False)
    op.create_index(op.f('ix_marketing_insights_user_id'), 'marketing_insights', ['user_id'], unique=False)
    op.create_table('user_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('total_conversation_time_minutes', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('messages_received', sa.Integer(), nullable=False),
    sa.Column('onboarding_progress', sa.Integer(), nullable=False),
    sa.Column('agents_interacted_with', sa.JSON(), nullable=False),
    sa.Column('features_used', sa.JSON(), nullable=False),
    sa.Column('business_insights_generated', sa.Integer(), nullable=False),
    sa.Column('actionable_recommendations', sa.Integer(), nullable=False),
    sa.Column('marketing_strategies_created', sa.Integer(), nullable=False),
    sa.Column('perplexity_api_calls', sa.Integer(), nullable=False),
    sa.Column('seranking_api_calls', sa.Integer(), nullable=False),
    sa.Column('openai_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_api_cost_usd', sa.Float(), nullable=False),
    sa.Column('average_satisfaction_score', sa.Float(), nullable=True),
    sa.Column('feedback_provided', sa.Integer(), nullable=False),
    sa.Column('positive_feedback_count', sa.Integer(), nullable=False),
    sa.Column('average_response_time_ms', sa.Float(), nullable=True),
    sa.Column('successful_interactions', sa.Integer(), nullable=False),
    sa.Column('failed_interactions', sa.Integer(), nullable=False),
    sa.Column('estimated_time_saved_hours', sa.Float(), nullable=False),
    sa.Column('marketing_roi_improvement', sa.Float(), nullable=True),
    sa.Column('cost_savings_estimated_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_analytics_date'), 'user_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_user_analytics_id'), 'user_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_user_analytics_month_start'), 'user_analytics', ['month_start'], unique=False)
    op.create_index(op.f('ix_user_analytics_user_id'), 'user_analytics', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_analytics_week_start'), 'user_analytics', ['week_start'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('industry_primary', sa.String(length=100), nullable=True),
    sa.Column('industry_secondary', sa.String(length=100), nullable=True),
    sa.Column('business_model', sa.String(length=50), nullable=True),
    sa.Column('target_market', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('communication_style', sa.String(length=50), nullable=False),
    sa.Column('response_format_preference', sa.String(length=50), nullable=False),
    sa.Column('marketing_experience_level', sa.String(length=50), nullable=False),
    sa.Column('primary_marketing_goals', sa.JSON(), nullable=True),
    sa.Column('marketing_budget_range', sa.String(length=50), nullable=True),
    sa.Column('current_marketing_channels', sa.JSON(), nullable=True),
    sa.Column('preferred_agent_personality', sa.String(length=50), nullable=False),
    sa.Column('detail_level_preference', sa.String(length=50), nullable=False),
    sa.Column('explanation_style', sa.String(length=50), nullable=False),
    sa.Column('learning_style', sa.String(length=50), nullable=True),
    sa.Column('areas_of_interest', sa.JSON(), nullable=True),
    sa.Column('skill_development_goals', sa.JSON(), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('decision_making_authority', sa.String(length=50), nullable=True),
    sa.Column('reporting_structure', sa.String(length=100), nullable=True),
    sa.Column('working_hours_start', sa.String(length=10), nullable=True),
    sa.Column('working_hours_end', sa.String(length=10), nullable=True),
    sa.Column('working_days', sa.JSON(), nullable=True),
    sa.Column('best_contact_time', sa.String(length=50), nullable=True),
    sa.Column('data_sharing_consent', sa.Boolean(), nullable=False),
    sa.Column('marketing_communications_consent', sa.Boolean(), nullable=False),
    sa.Column('analytics_consent', sa.Boolean(), nullable=False),
    sa.Column('profile_completion_percentage', sa.Integer(), nullable=False),
    sa.Column('last_profile_update', sa.DateTime(), nullable=True),
    sa.Column('custom_attributes', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('agent_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('tokens_consumed', sa.Integer(), nullable=True),
    sa.Column('api_calls_made', sa.Integer(), nullable=True),
    sa.Column('cost_incurred', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_interactions_agent_name'), 'agent_interactions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_interactions_conversation_id'), 'agent_interactions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_interactions_id'), 'agent_interactions', ['id'], unique=False)
    op.create_table('conversation_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('state_type', sa.String(length=50), nullable=False),
    sa.Column('previous_state', sa.String(length=100), nullable=True),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_states_conversation_id'), 'conversation_states', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_states_id'), 'conversation_states', ['id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('agent_confidence', sa.Float(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('cultural_context_applied', sa.Boolean(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('external_apis_used', sa.JSON(), nullable=True),
    sa.Column('api_response_data', sa.JSON(), nullable=True),
    sa.Column('user_feedback', sa.String(length=50), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('follow_up_questions', sa.JSON(), nullable=True),
    sa.Column('triggered_agent_handoff', sa.Boolean(), nullable=False),
    sa.Column('next_expected_action', sa.String(length=100), nullable=True),
    sa.Column('conversation_stage_transition', sa.String(length=100), nullable=True),
    sa.Column('intent_detected', sa.String(length=100), nullable=True),
    sa.Column('entities_extracted', sa.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_conversation_id'), 'conversation_turns', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_created_at'), 'conversation_turns', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_turns_id'), 'conversation_turns', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_user_id'), 'conversation_turns', ['user_id'], unique=False)
    op.alter_column('business_profiles', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('business_profiles', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('seranking_backlink_analyses', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('seranking_backlink_analyses', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('seranking_backlink_analyses', 'domain_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('seranking_domains', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('seranking_domains', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('preferred_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('onboarding_stage', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'trial_ends_at')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'onboarding_completed_at')
    op.drop_column('users', 'onboarding_stage')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'preferred_name')
    op.drop_column('users', 'title')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.alter_column('seranking_domains', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('seranking_domains', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('seranking_backlink_analyses', 'domain_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('seranking_backlink_analyses', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('seranking_backlink_analyses', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('business_profiles', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('business_profiles', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_conversation_turns_user_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_created_at'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_conversation_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_conversation_states_id'), table_name='conversation_states')
    op.drop_index(op.f('ix_conversation_states_conversation_id'), table_name='conversation_states')
    op.drop_table('conversation_states')
    op.drop_index(op.f('ix_agent_interactions_id'), table_name='agent_interactions')
    op.drop_index(op.f('ix_agent_interactions_conversation_id'), table_name='agent_interactions')
    op.drop_index(op.f('ix_agent_interactions_agent_name'), table_name='agent_interactions')
    op.drop_table('agent_interactions')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_analytics_week_start'), table_name='user_analytics')
    op.drop_index(op.f('ix_user_analytics_user_id'), table_name='user_analytics')
    op.drop_index(op.f('ix_user_analytics_month_start'), table_name='user_analytics')
    op.drop_index(op.f('ix_user_analytics_id'), table_name='user_analytics')
    op.drop_index(op.f('ix_user_analytics_date'), table_name='user_analytics')
    op.drop_table('user_analytics')
    op.drop_index(op.f('ix_marketing_insights_user_id'), table_name='marketing_insights')
    op.drop_index(op.f('ix_marketing_insights_id'), table_name='marketing_insights')
    op.drop_table('marketing_insights')
    op.drop_index(op.f('ix_cultural_contexts_id'), table_name='cultural_contexts')
    op.drop_table('cultural_contexts')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_date'), table_name='system_metrics')
    op.drop_table('system_metrics')
    # ### end Alembic commands ###
