name: Nightly Postgres Backup

on:
  schedule:
    - cron: '0 3 * * *'  # every day at 03:00 UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      PGPASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Dump database
        run: |
          pg_dump --dbname=${{ secrets.DATABASE_URL }} --format=custom --file=backup.dump
      - name: Upload dump artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgres-backup
          path: backup.dump
          retention-days: 7 