name: Deploy to Railway

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # no explicit dependency; runs after CI passes implicitly
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Railway
        uses: railwayapp/railway-cli@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          command: up 