name: Deploy (Helm)

on:
  push:
    branches: ["main"]
    paths:
      - "charts/**"
      - ".github/workflows/helm-release.yml"
      - "Dockerfile"
      - "README.md"
      - "app/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.30.0

      - name: Configure Kubeconfig
        run: |
          echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_BASE64 }}

      - name: Set image tag env
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy with Helm
        run: |
          helm upgrade --install morvo charts/morvo \
            --namespace morvo --create-namespace \
            --set image.repository=${{ secrets.REGISTRY_URL }}/morvo \
            --set image.tag=${IMAGE_TAG} 