name: Secret Scan (truffleHog)

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install truffleHog
        run: pip install trufflehog==3.69.0
      - name: Run secret scan on PR diff
        run: |
          trufflehog git --since-commit ${{ github.event.pull_request.base.sha }} --until-commit ${{ github.event.pull_request.head.sha }} --no-update . 