name: Container Security Scan

on:
  pull_request:
    paths:
      - "Dockerfile"
      - ".github/workflows/trivy.yml"
      - "app/**"

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: morvo:test
          push: false

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: morvo:test
          format: table
          severity: CRITICAL,HIGH 